// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: catalog-product.proto

package io.dmcapps.proto;

public interface BrandOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.dmcapps.proto.Brand)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string picture = 3;</code>
   * @return The picture.
   */
  java.lang.String getPicture();
  /**
   * <code>string picture = 3;</code>
   * @return The bytes for picture.
   */
  com.google.protobuf.ByteString
      getPictureBytes();

  /**
   * <code>.io.dmcapps.proto.Brand.Status status = 4;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.io.dmcapps.proto.Brand.Status status = 4;</code>
   * @return The status.
   */
  io.dmcapps.proto.Brand.Status getStatus();
}
