// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: catalog-product.proto

package io.dmcapps.proto;

public final class Catalog {
  private Catalog() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_dmcapps_proto_Category_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_dmcapps_proto_Category_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_dmcapps_proto_Brand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_dmcapps_proto_Brand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_dmcapps_proto_Product_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_dmcapps_proto_Product_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_dmcapps_proto_ProductResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_dmcapps_proto_ProductResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025catalog-product.proto\022\020io.dmcapps.prot" +
      "o\"\246\001\n\010Category\022\n\n\002id\030\001 \001(\003\022\016\n\006parent\030\002 \001" +
      "(\t\022\014\n\004name\030\003 \001(\t\0221\n\006status\030\004 \001(\0162!.io.dm" +
      "capps.proto.Category.Status\"=\n\006Status\022\013\n" +
      "\007PENDING\020\000\022\013\n\007CREATED\020\001\022\013\n\007UPDATED\020\002\022\014\n\010" +
      "REJECTED\020\003\"\241\001\n\005Brand\022\n\n\002id\030\001 \001(\003\022\014\n\004name" +
      "\030\002 \001(\t\022\017\n\007picture\030\003 \001(\t\022.\n\006status\030\004 \001(\0162" +
      "\036.io.dmcapps.proto.Brand.Status\"=\n\006Statu" +
      "s\022\013\n\007PENDING\020\000\022\013\n\007CREATED\020\001\022\013\n\007UPDATED\020\002" +
      "\022\014\n\010REJECTED\020\003\"\373\001\n\007Product\022\n\n\002id\030\001 \001(\t\022\014" +
      "\n\004name\030\002 \001(\t\022&\n\005brand\030\003 \001(\0132\027.io.dmcapps" +
      ".proto.Brand\022,\n\010category\030\004 \001(\0132\032.io.dmca" +
      "pps.proto.Category\022\017\n\007picture\030\005 \001(\t\0220\n\006s" +
      "tatus\030\006 \001(\0162 .io.dmcapps.proto.Product.S" +
      "tatus\"=\n\006Status\022\013\n\007PENDING\020\000\022\013\n\007CREATED\020" +
      "\001\022\013\n\007UPDATED\020\002\022\014\n\010REJECTED\020\003\">\n\017ProductR" +
      "esponse\022+\n\010products\030\001 \003(\0132\031.io.dmcapps.p" +
      "roto.ProductB\013B\007CatalogP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_io_dmcapps_proto_Category_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_dmcapps_proto_Category_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_dmcapps_proto_Category_descriptor,
        new java.lang.String[] { "Id", "Parent", "Name", "Status", });
    internal_static_io_dmcapps_proto_Brand_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_io_dmcapps_proto_Brand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_dmcapps_proto_Brand_descriptor,
        new java.lang.String[] { "Id", "Name", "Picture", "Status", });
    internal_static_io_dmcapps_proto_Product_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_io_dmcapps_proto_Product_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_dmcapps_proto_Product_descriptor,
        new java.lang.String[] { "Id", "Name", "Brand", "Category", "Picture", "Status", });
    internal_static_io_dmcapps_proto_ProductResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_io_dmcapps_proto_ProductResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_dmcapps_proto_ProductResponse_descriptor,
        new java.lang.String[] { "Products", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
