// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: catalog-product.proto

package io.dmcapps.proto;

public interface CategoryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.dmcapps.proto.Category)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string parent = 2;</code>
   * @return The parent.
   */
  java.lang.String getParent();
  /**
   * <code>string parent = 2;</code>
   * @return The bytes for parent.
   */
  com.google.protobuf.ByteString
      getParentBytes();

  /**
   * <code>string name = 3;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 3;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.io.dmcapps.proto.Category.Status status = 4;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.io.dmcapps.proto.Category.Status status = 4;</code>
   * @return The status.
   */
  io.dmcapps.proto.Category.Status getStatus();
}
