// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: catalog-product.proto

package io.dmcapps.proto;

/**
 * Protobuf type {@code io.dmcapps.proto.Product}
 */
public  final class Product extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:io.dmcapps.proto.Product)
    ProductOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Product.newBuilder() to construct.
  private Product(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Product() {
    id_ = "";
    name_ = "";
    picture_ = "";
    status_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Product();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Product(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 26: {
            io.dmcapps.proto.Brand.Builder subBuilder = null;
            if (brand_ != null) {
              subBuilder = brand_.toBuilder();
            }
            brand_ = input.readMessage(io.dmcapps.proto.Brand.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(brand_);
              brand_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            io.dmcapps.proto.Category.Builder subBuilder = null;
            if (category_ != null) {
              subBuilder = category_.toBuilder();
            }
            category_ = input.readMessage(io.dmcapps.proto.Category.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(category_);
              category_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            picture_ = s;
            break;
          }
          case 48: {
            int rawValue = input.readEnum();

            status_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.dmcapps.proto.Catalog.internal_static_io_dmcapps_proto_Product_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.dmcapps.proto.Catalog.internal_static_io_dmcapps_proto_Product_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.dmcapps.proto.Product.class, io.dmcapps.proto.Product.Builder.class);
  }

  /**
   * Protobuf enum {@code io.dmcapps.proto.Product.Status}
   */
  public enum Status
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>PENDING = 0;</code>
     */
    PENDING(0),
    /**
     * <code>CREATED = 1;</code>
     */
    CREATED(1),
    /**
     * <code>UPDATED = 2;</code>
     */
    UPDATED(2),
    /**
     * <code>REJECTED = 3;</code>
     */
    REJECTED(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>PENDING = 0;</code>
     */
    public static final int PENDING_VALUE = 0;
    /**
     * <code>CREATED = 1;</code>
     */
    public static final int CREATED_VALUE = 1;
    /**
     * <code>UPDATED = 2;</code>
     */
    public static final int UPDATED_VALUE = 2;
    /**
     * <code>REJECTED = 3;</code>
     */
    public static final int REJECTED_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Status valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Status forNumber(int value) {
      switch (value) {
        case 0: return PENDING;
        case 1: return CREATED;
        case 2: return UPDATED;
        case 3: return REJECTED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Status>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Status> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Status>() {
            public Status findValueByNumber(int number) {
              return Status.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return io.dmcapps.proto.Product.getDescriptor().getEnumTypes().get(0);
    }

    private static final Status[] VALUES = values();

    public static Status valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Status(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:io.dmcapps.proto.Product.Status)
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BRAND_FIELD_NUMBER = 3;
  private io.dmcapps.proto.Brand brand_;
  /**
   * <code>.io.dmcapps.proto.Brand brand = 3;</code>
   * @return Whether the brand field is set.
   */
  public boolean hasBrand() {
    return brand_ != null;
  }
  /**
   * <code>.io.dmcapps.proto.Brand brand = 3;</code>
   * @return The brand.
   */
  public io.dmcapps.proto.Brand getBrand() {
    return brand_ == null ? io.dmcapps.proto.Brand.getDefaultInstance() : brand_;
  }
  /**
   * <code>.io.dmcapps.proto.Brand brand = 3;</code>
   */
  public io.dmcapps.proto.BrandOrBuilder getBrandOrBuilder() {
    return getBrand();
  }

  public static final int CATEGORY_FIELD_NUMBER = 4;
  private io.dmcapps.proto.Category category_;
  /**
   * <code>.io.dmcapps.proto.Category category = 4;</code>
   * @return Whether the category field is set.
   */
  public boolean hasCategory() {
    return category_ != null;
  }
  /**
   * <code>.io.dmcapps.proto.Category category = 4;</code>
   * @return The category.
   */
  public io.dmcapps.proto.Category getCategory() {
    return category_ == null ? io.dmcapps.proto.Category.getDefaultInstance() : category_;
  }
  /**
   * <code>.io.dmcapps.proto.Category category = 4;</code>
   */
  public io.dmcapps.proto.CategoryOrBuilder getCategoryOrBuilder() {
    return getCategory();
  }

  public static final int PICTURE_FIELD_NUMBER = 5;
  private volatile java.lang.Object picture_;
  /**
   * <code>string picture = 5;</code>
   * @return The picture.
   */
  public java.lang.String getPicture() {
    java.lang.Object ref = picture_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      picture_ = s;
      return s;
    }
  }
  /**
   * <code>string picture = 5;</code>
   * @return The bytes for picture.
   */
  public com.google.protobuf.ByteString
      getPictureBytes() {
    java.lang.Object ref = picture_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      picture_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 6;
  private int status_;
  /**
   * <code>.io.dmcapps.proto.Product.Status status = 6;</code>
   * @return The enum numeric value on the wire for status.
   */
  public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.io.dmcapps.proto.Product.Status status = 6;</code>
   * @return The status.
   */
  public io.dmcapps.proto.Product.Status getStatus() {
    @SuppressWarnings("deprecation")
    io.dmcapps.proto.Product.Status result = io.dmcapps.proto.Product.Status.valueOf(status_);
    return result == null ? io.dmcapps.proto.Product.Status.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (brand_ != null) {
      output.writeMessage(3, getBrand());
    }
    if (category_ != null) {
      output.writeMessage(4, getCategory());
    }
    if (!getPictureBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, picture_);
    }
    if (status_ != io.dmcapps.proto.Product.Status.PENDING.getNumber()) {
      output.writeEnum(6, status_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (brand_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getBrand());
    }
    if (category_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getCategory());
    }
    if (!getPictureBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, picture_);
    }
    if (status_ != io.dmcapps.proto.Product.Status.PENDING.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, status_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.dmcapps.proto.Product)) {
      return super.equals(obj);
    }
    io.dmcapps.proto.Product other = (io.dmcapps.proto.Product) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (hasBrand() != other.hasBrand()) return false;
    if (hasBrand()) {
      if (!getBrand()
          .equals(other.getBrand())) return false;
    }
    if (hasCategory() != other.hasCategory()) return false;
    if (hasCategory()) {
      if (!getCategory()
          .equals(other.getCategory())) return false;
    }
    if (!getPicture()
        .equals(other.getPicture())) return false;
    if (status_ != other.status_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    if (hasBrand()) {
      hash = (37 * hash) + BRAND_FIELD_NUMBER;
      hash = (53 * hash) + getBrand().hashCode();
    }
    if (hasCategory()) {
      hash = (37 * hash) + CATEGORY_FIELD_NUMBER;
      hash = (53 * hash) + getCategory().hashCode();
    }
    hash = (37 * hash) + PICTURE_FIELD_NUMBER;
    hash = (53 * hash) + getPicture().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.dmcapps.proto.Product parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.dmcapps.proto.Product parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.dmcapps.proto.Product parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.dmcapps.proto.Product parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.dmcapps.proto.Product parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.dmcapps.proto.Product parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.dmcapps.proto.Product parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.dmcapps.proto.Product parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.dmcapps.proto.Product parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.dmcapps.proto.Product parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.dmcapps.proto.Product parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.dmcapps.proto.Product parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.dmcapps.proto.Product prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code io.dmcapps.proto.Product}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.dmcapps.proto.Product)
      io.dmcapps.proto.ProductOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.dmcapps.proto.Catalog.internal_static_io_dmcapps_proto_Product_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.dmcapps.proto.Catalog.internal_static_io_dmcapps_proto_Product_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.dmcapps.proto.Product.class, io.dmcapps.proto.Product.Builder.class);
    }

    // Construct using io.dmcapps.proto.Product.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      name_ = "";

      if (brandBuilder_ == null) {
        brand_ = null;
      } else {
        brand_ = null;
        brandBuilder_ = null;
      }
      if (categoryBuilder_ == null) {
        category_ = null;
      } else {
        category_ = null;
        categoryBuilder_ = null;
      }
      picture_ = "";

      status_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.dmcapps.proto.Catalog.internal_static_io_dmcapps_proto_Product_descriptor;
    }

    @java.lang.Override
    public io.dmcapps.proto.Product getDefaultInstanceForType() {
      return io.dmcapps.proto.Product.getDefaultInstance();
    }

    @java.lang.Override
    public io.dmcapps.proto.Product build() {
      io.dmcapps.proto.Product result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.dmcapps.proto.Product buildPartial() {
      io.dmcapps.proto.Product result = new io.dmcapps.proto.Product(this);
      result.id_ = id_;
      result.name_ = name_;
      if (brandBuilder_ == null) {
        result.brand_ = brand_;
      } else {
        result.brand_ = brandBuilder_.build();
      }
      if (categoryBuilder_ == null) {
        result.category_ = category_;
      } else {
        result.category_ = categoryBuilder_.build();
      }
      result.picture_ = picture_;
      result.status_ = status_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.dmcapps.proto.Product) {
        return mergeFrom((io.dmcapps.proto.Product)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.dmcapps.proto.Product other) {
      if (other == io.dmcapps.proto.Product.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.hasBrand()) {
        mergeBrand(other.getBrand());
      }
      if (other.hasCategory()) {
        mergeCategory(other.getCategory());
      }
      if (!other.getPicture().isEmpty()) {
        picture_ = other.picture_;
        onChanged();
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.dmcapps.proto.Product parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.dmcapps.proto.Product) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private io.dmcapps.proto.Brand brand_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.dmcapps.proto.Brand, io.dmcapps.proto.Brand.Builder, io.dmcapps.proto.BrandOrBuilder> brandBuilder_;
    /**
     * <code>.io.dmcapps.proto.Brand brand = 3;</code>
     * @return Whether the brand field is set.
     */
    public boolean hasBrand() {
      return brandBuilder_ != null || brand_ != null;
    }
    /**
     * <code>.io.dmcapps.proto.Brand brand = 3;</code>
     * @return The brand.
     */
    public io.dmcapps.proto.Brand getBrand() {
      if (brandBuilder_ == null) {
        return brand_ == null ? io.dmcapps.proto.Brand.getDefaultInstance() : brand_;
      } else {
        return brandBuilder_.getMessage();
      }
    }
    /**
     * <code>.io.dmcapps.proto.Brand brand = 3;</code>
     */
    public Builder setBrand(io.dmcapps.proto.Brand value) {
      if (brandBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        brand_ = value;
        onChanged();
      } else {
        brandBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.io.dmcapps.proto.Brand brand = 3;</code>
     */
    public Builder setBrand(
        io.dmcapps.proto.Brand.Builder builderForValue) {
      if (brandBuilder_ == null) {
        brand_ = builderForValue.build();
        onChanged();
      } else {
        brandBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.io.dmcapps.proto.Brand brand = 3;</code>
     */
    public Builder mergeBrand(io.dmcapps.proto.Brand value) {
      if (brandBuilder_ == null) {
        if (brand_ != null) {
          brand_ =
            io.dmcapps.proto.Brand.newBuilder(brand_).mergeFrom(value).buildPartial();
        } else {
          brand_ = value;
        }
        onChanged();
      } else {
        brandBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.io.dmcapps.proto.Brand brand = 3;</code>
     */
    public Builder clearBrand() {
      if (brandBuilder_ == null) {
        brand_ = null;
        onChanged();
      } else {
        brand_ = null;
        brandBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.io.dmcapps.proto.Brand brand = 3;</code>
     */
    public io.dmcapps.proto.Brand.Builder getBrandBuilder() {
      
      onChanged();
      return getBrandFieldBuilder().getBuilder();
    }
    /**
     * <code>.io.dmcapps.proto.Brand brand = 3;</code>
     */
    public io.dmcapps.proto.BrandOrBuilder getBrandOrBuilder() {
      if (brandBuilder_ != null) {
        return brandBuilder_.getMessageOrBuilder();
      } else {
        return brand_ == null ?
            io.dmcapps.proto.Brand.getDefaultInstance() : brand_;
      }
    }
    /**
     * <code>.io.dmcapps.proto.Brand brand = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.dmcapps.proto.Brand, io.dmcapps.proto.Brand.Builder, io.dmcapps.proto.BrandOrBuilder> 
        getBrandFieldBuilder() {
      if (brandBuilder_ == null) {
        brandBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.dmcapps.proto.Brand, io.dmcapps.proto.Brand.Builder, io.dmcapps.proto.BrandOrBuilder>(
                getBrand(),
                getParentForChildren(),
                isClean());
        brand_ = null;
      }
      return brandBuilder_;
    }

    private io.dmcapps.proto.Category category_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.dmcapps.proto.Category, io.dmcapps.proto.Category.Builder, io.dmcapps.proto.CategoryOrBuilder> categoryBuilder_;
    /**
     * <code>.io.dmcapps.proto.Category category = 4;</code>
     * @return Whether the category field is set.
     */
    public boolean hasCategory() {
      return categoryBuilder_ != null || category_ != null;
    }
    /**
     * <code>.io.dmcapps.proto.Category category = 4;</code>
     * @return The category.
     */
    public io.dmcapps.proto.Category getCategory() {
      if (categoryBuilder_ == null) {
        return category_ == null ? io.dmcapps.proto.Category.getDefaultInstance() : category_;
      } else {
        return categoryBuilder_.getMessage();
      }
    }
    /**
     * <code>.io.dmcapps.proto.Category category = 4;</code>
     */
    public Builder setCategory(io.dmcapps.proto.Category value) {
      if (categoryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        category_ = value;
        onChanged();
      } else {
        categoryBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.io.dmcapps.proto.Category category = 4;</code>
     */
    public Builder setCategory(
        io.dmcapps.proto.Category.Builder builderForValue) {
      if (categoryBuilder_ == null) {
        category_ = builderForValue.build();
        onChanged();
      } else {
        categoryBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.io.dmcapps.proto.Category category = 4;</code>
     */
    public Builder mergeCategory(io.dmcapps.proto.Category value) {
      if (categoryBuilder_ == null) {
        if (category_ != null) {
          category_ =
            io.dmcapps.proto.Category.newBuilder(category_).mergeFrom(value).buildPartial();
        } else {
          category_ = value;
        }
        onChanged();
      } else {
        categoryBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.io.dmcapps.proto.Category category = 4;</code>
     */
    public Builder clearCategory() {
      if (categoryBuilder_ == null) {
        category_ = null;
        onChanged();
      } else {
        category_ = null;
        categoryBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.io.dmcapps.proto.Category category = 4;</code>
     */
    public io.dmcapps.proto.Category.Builder getCategoryBuilder() {
      
      onChanged();
      return getCategoryFieldBuilder().getBuilder();
    }
    /**
     * <code>.io.dmcapps.proto.Category category = 4;</code>
     */
    public io.dmcapps.proto.CategoryOrBuilder getCategoryOrBuilder() {
      if (categoryBuilder_ != null) {
        return categoryBuilder_.getMessageOrBuilder();
      } else {
        return category_ == null ?
            io.dmcapps.proto.Category.getDefaultInstance() : category_;
      }
    }
    /**
     * <code>.io.dmcapps.proto.Category category = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.dmcapps.proto.Category, io.dmcapps.proto.Category.Builder, io.dmcapps.proto.CategoryOrBuilder> 
        getCategoryFieldBuilder() {
      if (categoryBuilder_ == null) {
        categoryBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.dmcapps.proto.Category, io.dmcapps.proto.Category.Builder, io.dmcapps.proto.CategoryOrBuilder>(
                getCategory(),
                getParentForChildren(),
                isClean());
        category_ = null;
      }
      return categoryBuilder_;
    }

    private java.lang.Object picture_ = "";
    /**
     * <code>string picture = 5;</code>
     * @return The picture.
     */
    public java.lang.String getPicture() {
      java.lang.Object ref = picture_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        picture_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string picture = 5;</code>
     * @return The bytes for picture.
     */
    public com.google.protobuf.ByteString
        getPictureBytes() {
      java.lang.Object ref = picture_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        picture_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string picture = 5;</code>
     * @param value The picture to set.
     * @return This builder for chaining.
     */
    public Builder setPicture(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      picture_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string picture = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPicture() {
      
      picture_ = getDefaultInstance().getPicture();
      onChanged();
      return this;
    }
    /**
     * <code>string picture = 5;</code>
     * @param value The bytes for picture to set.
     * @return This builder for chaining.
     */
    public Builder setPictureBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      picture_ = value;
      onChanged();
      return this;
    }

    private int status_ = 0;
    /**
     * <code>.io.dmcapps.proto.Product.Status status = 6;</code>
     * @return The enum numeric value on the wire for status.
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.io.dmcapps.proto.Product.Status status = 6;</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.io.dmcapps.proto.Product.Status status = 6;</code>
     * @return The status.
     */
    public io.dmcapps.proto.Product.Status getStatus() {
      @SuppressWarnings("deprecation")
      io.dmcapps.proto.Product.Status result = io.dmcapps.proto.Product.Status.valueOf(status_);
      return result == null ? io.dmcapps.proto.Product.Status.UNRECOGNIZED : result;
    }
    /**
     * <code>.io.dmcapps.proto.Product.Status status = 6;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(io.dmcapps.proto.Product.Status value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.io.dmcapps.proto.Product.Status status = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:io.dmcapps.proto.Product)
  }

  // @@protoc_insertion_point(class_scope:io.dmcapps.proto.Product)
  private static final io.dmcapps.proto.Product DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.dmcapps.proto.Product();
  }

  public static io.dmcapps.proto.Product getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Product>
      PARSER = new com.google.protobuf.AbstractParser<Product>() {
    @java.lang.Override
    public Product parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Product(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Product> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Product> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.dmcapps.proto.Product getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

