// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: catalog-product.proto

package io.dmcapps.proto;

public interface ProductOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.dmcapps.proto.Product)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.io.dmcapps.proto.Brand brand = 3;</code>
   * @return Whether the brand field is set.
   */
  boolean hasBrand();
  /**
   * <code>.io.dmcapps.proto.Brand brand = 3;</code>
   * @return The brand.
   */
  io.dmcapps.proto.Brand getBrand();
  /**
   * <code>.io.dmcapps.proto.Brand brand = 3;</code>
   */
  io.dmcapps.proto.BrandOrBuilder getBrandOrBuilder();

  /**
   * <code>.io.dmcapps.proto.Category category = 4;</code>
   * @return Whether the category field is set.
   */
  boolean hasCategory();
  /**
   * <code>.io.dmcapps.proto.Category category = 4;</code>
   * @return The category.
   */
  io.dmcapps.proto.Category getCategory();
  /**
   * <code>.io.dmcapps.proto.Category category = 4;</code>
   */
  io.dmcapps.proto.CategoryOrBuilder getCategoryOrBuilder();

  /**
   * <code>string picture = 5;</code>
   * @return The picture.
   */
  java.lang.String getPicture();
  /**
   * <code>string picture = 5;</code>
   * @return The bytes for picture.
   */
  com.google.protobuf.ByteString
      getPictureBytes();

  /**
   * <code>.io.dmcapps.proto.Product.Status status = 6;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.io.dmcapps.proto.Product.Status status = 6;</code>
   * @return The status.
   */
  io.dmcapps.proto.Product.Status getStatus();
}
